<?php

namespace ContainerYKn4S9y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VZYzWW3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VZYzWW3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VZYzWW3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRepository' => ['privates', 'App\\Repository\\OffreClientRepository', 'getOffreClientRepositoryService', true],
            'pdfService' => ['privates', 'App\\services\\PdfService', 'getPdfServiceService', true],
        ], [
            'clientRepository' => 'App\\Repository\\OffreClientRepository',
            'pdfService' => 'App\\services\\PdfService',
        ]);
    }
}
