<?php

namespace ContainerYKn4S9y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\services\PdfService' shared autowired service.
     *
     * @return \App\services\PdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'services'.\DIRECTORY_SEPARATOR.'PdfService.php';

        return $container->privates['App\\services\\PdfService'] = new \App\services\PdfService();
    }
}
