<?php

namespace ContainerYKn4S9y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirectOnAccessDeniedSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\RedirectOnAccessDeniedSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\RedirectOnAccessDeniedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'RedirectOnAccessDeniedSubscriber.php';

        return $container->privates['App\\EventSubscriber\\RedirectOnAccessDeniedSubscriber'] = new \App\EventSubscriber\RedirectOnAccessDeniedSubscriber(($container->services['router'] ?? self::getRouterService($container)));
    }
}
